language: java

script:
  - docker build -t="ucontas-api":latest .

before_install:
  - sudo apt-get update
  - echo "---------| Generating package with maven!!!  |---------"
  - mvn clean package

before_deploy:
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: script
  script:
    echo "---------| Generating image tags !!!  |---------";
    docker tag ucontas-api:latest $DOCKER_USERNAME/ucontas-api:$TRAVIS_JOB_NUMBER;
    docker tag ucontas-api:latest $DOCKER_USERNAME/ucontas-api:latest;
    echo "---------| Sending to Docker HUB !!!  |---------"
    docker push $DOCKER_USERNAME/ucontas-api:$TRAVIS_JOB_NUMBER;
    docker push $DOCKER_USERNAME/ucontas-api:latest;
    echo "---------| Image successfully sent to Docker HUB !!!  |---------";
  on:
    brach: master
notifications:
  email: false